[program:vllm]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/vllm.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
