# -----------------------------------------------------------------------
# Orchestrator SSH key pair
#
# An Ed25519 key pair is generated by Terraform and stored in Secrets
# Manager.  The ECS task definition injects the private key as an
# environment variable (ORCHESTRATOR_SSH_PRIVATE_KEY) so the orchestrator
# can SSH into vast.ai worker instances to tail /tmp/vllm.log during
# startup rather than waiting for the vast.ai log API.
#
# The public key is registered with the vast.ai account by the
# orchestrator on startup (via vast.ai /api/v0/keys/) and injected into
# each new instance's authorized_keys via EXTRA_COMMANDS.
#
# Key rotation: run `terraform apply -replace=tls_private_key.orchestrator_ssh`
# The new secret version is picked up on the next ECS task restart.
# -----------------------------------------------------------------------

resource "tls_private_key" "orchestrator_ssh" {
  algorithm = "ED25519"
}

# ── Secrets Manager ───────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "orchestrator_ssh_key" {
  name        = "${local.name_prefix}/orchestrator-ssh-private-key"
  description = "Ed25519 OpenSSH private key — orchestrator SSH access to vast.ai workers"

  # Immediate deletion — no recovery window (key is fully reproducible via
  # `terraform apply -replace=tls_private_key.orchestrator_ssh`).
  recovery_window_in_days = 0

  tags = { Name = "${local.name_prefix}-orchestrator-ssh-key" }
}

resource "aws_secretsmanager_secret_version" "orchestrator_ssh_key" {
  secret_id = aws_secretsmanager_secret.orchestrator_ssh_key.id
  # OpenSSH format: "-----BEGIN OPENSSH PRIVATE KEY-----\n...\n-----END OPENSSH PRIVATE KEY-----\n"
  # asyncssh.import_private_key() accepts this format directly.
  secret_string = tls_private_key.orchestrator_ssh.private_key_openssh
}
